#pragma once

enum ResourceKey
{
    ActionMark,
    CanMoveMark,
    CanTakeMark,

    StoneBlackChessBoard,
    StoneBlueChessBoard,
    StoneGreyChessBoard,
    WoodChessBoard,

    WoodPieceBishopB,
    WoodPieceBishopW,
    WoodPieceKingB,
    WoodPieceKingW,
    WoodPieceKnightB,
    WoodPieceKnightW,
    WoodPiecePawnB,
    WoodPiecePawnW,
    WoodPieceQueenB,
    WoodPieceQueenW,
    WoodPieceRookB,
    WoodPieceRookW,

    StonePieceBishopB,
    StonePieceBishopW,
    StonePieceKingB,
    StonePieceKingW,
    StonePieceKnightB,
    StonePieceKnightW,
    StonePiecePawnB,
    StonePiecePawnW,
    StonePieceQueenB,
    StonePieceQueenW,
    StonePieceRookB,
    StonePieceRookW,

    WoodSymbolBishopB,
    WoodSymbolBishopW,
    WoodSymbolKingB,
    WoodSymbolKingW,
    WoodSymbolKnightB,
    WoodSymbolKnightW,
    WoodSymbolPawnB,
    WoodSymbolPawnW,
    WoodSymbolQueenB,
    WoodSymbolQueenW,
    WoodSymbolRookB,
    WoodSymbolRookW,

    StoneSymbolBishopB,
    StoneSymbolBishopW,
    StoneSymbolKingB,
    StoneSymbolKingW,
    StoneSymbolKnightB,
    StoneSymbolKnightW,
    StoneSymbolPawnB,
    StoneSymbolPawnW,
    StoneSymbolQueenB,
    StoneSymbolQueenW,
    StoneSymbolRookB,
    StoneSymbolRookW,
};